### PR TITLE
Small fixes to Debian packaging

### PR DESCRIPTION
**Pull request by valholl**
While trying to build a deb I've found it had a number of issues including missing dependencies and a wrong version number,

This pull request fixes those and adds a few other trivial changes that fix some warnings.

It has been tested under both stretch (current testing) and jessie (current stable).

Please let me know if you need me to change anything

### CODE REVIEW

**Comment by sevan** [comment]
Hi,
Thanks for the submission!
Where does the python & python-gtk dependency come from?

**Comment by valholl** [comment]
On 2017-01-05 at 16:27:40 -0800, Sevan Janiyan wrote:
> Where does the python & python-gtk dependency come from?

from conf/CoovaChilliLib.py

maybe it should be a Recommends instead of a Depend? (if so, I'll update
the PR)

-- 
Elena ``of Valhalla''

**Comment by pinkra** [comment]
yes, it should be optional..

**Comment by sevan** [comment]
@valholl if the python & gtk dependencies aren't installed, what functionality do you lose in coova?

**Comment by valholl** [comment]
@sevan  Actually, I don't know: I was trying to build the deb package to install coova and try it out, and most of the contents of the PR came from the suggestions of some QA tools usually used in debian to check the debs (and I tried to select only the ones that are usually quite safe; there were others that may or may not be good suggestions that I skipped)

**Comment by valholl** [comment]
I updated the PR to turn that dependency in a Suggests, since if I understand correctly those python files aren't really needed?

**Pull request merged**
