### PR TITLE
Implement RFC 7710 - Captive Portal URI DHCP option

### PR DESCRIPTION
**Pull request by wlanmac**
Feature request #215

### CODE REVIEW

**Comment by gufmar** [comment]
Just to link (and read) the RFC: https://tools.ietf.org/html/rfc7710

It would be ok to have such an option. The question is if the 2+1 main mobile OS will support it

**Comment by wlanmac** [comment]
#91 for reference.
Yes, RFC 7710 does not address **notification**. While it is useful for indicating **configuration**, it will likely only be useful in combination with a notification mechanism like https://www.ietf.org/archive/id/draft-wkumari-capport-icmp-unreach-01.txt

**Comment by pinkra** [comment]
Some dhcp server for linux that support this feature?

**Comment by Spomky** [comment]
@pinkra DNSMasq seems to support it (see https://forum.ubuntu-fr.org/viewtopic.php?id=1987199 - in French)

**Comment by pinkra** [comment]
Uhm.. it seems it doesn't have a full support... is it useful to have this feature in some case?

**Comment by Spomky** [comment]
This is a quite new RFC (was published by the end of the previous year).
Servers and also clients have not yet implemented this feature and its use is somehow experimental.

If you think this is not a yet ready to be implemented in that project, then you could merge it into a next revision.

**Pull request merged**
