### PR TITLE
Logging API for coova-chilli

### PR DESCRIPTION
**Pull request by gbaligh**
This is my proposal for Logging interface:
- Default logging
- Logging per module
- Environment variable to change level per module

This pull is for review

### CODE REVIEW

**Comment by sevan** [comment]
Hi,
Just a heads up about the license in your cod, have you considered the licensing terms in the contributors agreement? (double checking in case)

**Comment by gbaligh** [comment]
Ok, I'll use this one.
What do you think about the interface, technically speaking ?

**Comment by sevan** [comment]
I'll try and take a look next week. Perhaps, for the sake of discussion, why is this needed & what does it improve over the use of `syslog(3)`

**Comment by gbaligh** [comment]
`syslog(3)` will be the base of all logging.
Advantages:
- Debug one module and not all chilli modules
- Avoid wrapping any call to syslog() by _options.debug
- One central module for logging manager, if we need to change something for logging, it will be easier.

**Pull request closed without merging**
