### PR TITLE
Sh bash

### PR DESCRIPTION
**Pull request by sevan**
Another /bin/sh -> /usr/bin/env bash

### CODE REVIEW

**Comment by nzamps** [comment]
What about systems without bash ? - this doesn't seem to work.

**Comment by sevan** [comment]
out of curiosity, what shell are you likely to find on your systems?
I'm testing with primarily pdksh here but looking at alchemist as well.

**Comment by nzamps** [comment]
Our smaller system use busybox so SHELL=/bin/ash

**Comment by sevan** [comment]
That would create further hurdles with having to deal with login shell / executing shell. I reverted these commits, apologies if I caused any inconvenience.

**Pull request merged**
