### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by sevan**

### CODE REVIEW

**Comment by ynezz** [comment]
@sevan Please can you read our updated [CONTRIBUTING.md guide](https://github.com/coova/coova-chilli/blob/master/CONTRIBUTING.md#pull-requests) and try to comply with it?

* you don't need to add information about every modified file in the commit message like `modified:   .travis.yml` as this is clearly visible from the commit, it's duplicate information
* you should add your `Signed-off-by:` line to every commit, it's easy with `git commit -s`

**Comment by sevan** [comment]
Being a member of project implies working under the compliance of the terms, doesn't it? (happy to add the signing off bit).
Regarding the duplication of information, a matter of taste?

**Comment by ynezz** [comment]
@sevan 

> Being a member of project implies working under the compliance of the terms, doesn't it?

IANAL, but if this is the case, you should probably ask @wlanmac  and modify [CONTRIBUTING.md](https://github.com/coova/coova-chilli/blob/master/CONTRIBUTING.md#pull-requests) accordingly to make it clear.

> Regarding the duplication of information, a matter of taste?

It's a well-established convention to not do this in projects managed by VCS as this information is already contained in the VCS metadata and it could be read back easily once it's needed using `git log --stat` for example.

Well, to make it clear and explicit, we should probably add link to (How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/](http://chris.beams.io/posts/git-commit/) (or just take out some small summary) to our [CONTRIBUTING.md](https://github.com/coova/coova-chilli/blob/master/CONTRIBUTING.md#pull-requests).

**Comment by sevan** [comment]
how about less bureaucracy?

**Comment by ynezz** [comment]
@sevan If you look at #90 it's clear, that we need some standards or rules, otherwise its going to be a unmaintanable mess. Does it means more bureaucracy, maybe, but it's being done for a better quality of code etc.

**Comment by sevan** [comment]
Ticket #90 is about coding standards. I would like to see your contributions in that discussion rather than spending the energy on nit picking. Bureaucracy is not going to impact the quality of the code in the actual commit.

**Pull request merged**
